- name: Remove old monitor-nginx.conf if exists
  file:
    path: /etc/nginx/conf.d/monitor-nginx.conf
    state: absent
  tags: [monitor_nginx]

- name: Add prom-zone configuration to ssl.conf
  blockinfile:
    path: /etc/nginx/conf.d/ssl.conf
    insertbefore: '    error_page 404 /404.html;'
    block: |
      {% if monitor_vip is defined and monitor_vip and monitor_access_port is defined and monitor_access_port %}
          location = /prom-zone { return 301 /prom-zone/; }
          location /prom-zone/ {
              proxy_pass http://{{ monitor_vip }}:{{ monitor_access_port }}/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_http_version 1.1;
              proxy_set_header Connection "";
              proxy_buffering off;
              client_max_body_size 0;
              proxy_read_timeout 3600s;
              proxy_redirect off;
          }
      {% endif %}
    marker: "    # {mark} ANSIBLE MANAGED BLOCK - prom-zone"
  tags: [monitor_nginx]

- name: reload nginx service
  systemd:
    name: nginx
    state: reloaded
  tags: [monitor_nginx]
