- name: monitor nginx ssl config
  template:
    src: monitor-nginx.conf.j2
    dest: /etc/nginx/conf.d/monitor-nginx.conf
  tags: [monitor_nginx]

- name: start monitor nginx service
  systemd:
    name: monitor-nginx
    enabled: yes
    daemon_reload: yes
    state: restarted
  tags: [monitor_nginx]
