network_device: ens5
vnc_device: ens5
admin_passwd: passw0rd
db_passwd: passw0rd
dns_server: 8.8.8.8
cpu_ratio: 1
mem_ratio: 1
disk_ratio: 1
domain_name: example.com
monitor_vip: 10.10.10.176
monitor_monitor_access_port: 9090
smtp_host: "smtp.test.com:465"
smtp_hello: "smtp.test.com"
alert_sender: "cloud_msg@test.com"
smtp_user: "cloud_msg@test.com"
smtp_pass: "123456"
receiver_name: "test_alert"
alert_recipient: "test@raksmart.com"
slack_webhook_url: "https://hooks.slack.com/services/test/example/123456"
alert_webhook_url: "10.10.10.171:8255"
