- name: Set prometheus_server_ip from monitor group
  set_fact:
    prometheus_server_ip: "{{ hostvars[groups['monitor'][0]]['ansible_host'] }}"

- name: Ensure remote_write for billing metrics is present
  delegate_to: "{{ prometheus_server_ip }}"
  become: true
  blockinfile:
    path: /etc/prometheus/prometheus.yml
    marker: "# {mark} ANSIBLE MANAGED BLOCK - remote_write for billing"
    insertafter: '^evaluation_interval:'
    block: |
      remote_write:
        - url: "{{ metering_server_url }}"
          tls_config:
            insecure_skip_verify: true
          queue_config:
            batch_send_deadline: 5m
            max_samples_per_send: 10000
            max_shards: 1
          write_relabel_configs:
            - source_labels: [__name__]
              regex: 'libvirt_domain_info_vstate|domain_north_south_.*|libvirt_domain_info_virtual_cpus|libvirt_domain_info_maximum_memory_bytes|libvirt_domain_block_stats_capacity_bytes|wds_volume_size_bytes|vm_instance_map'
              action: keep
  when: metering_server_url is defined

- name: Restart prometheus after config change
  delegate_to: "{{ prometheus_server_ip }}"
  systemd:
    name: prometheus
    state: restarted
  when:
    - metering_server_url is defined
